import Footer from "@/components/Footer";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { addCampaign, getLastCampignId } from "@/services/web3Service";

export default function Create() {
  // Mudança: Inicializei o estado `campaign` com strings vazias para evitar que o valor mude de undefined para um valor definido.
  const [campaign, setCampaign] = useState({
    title: "",          // Título começa como string vazia
    description: "",    // Descrição começa como string vazia
    imageUrl: "",       // URL da imagem começa como string vazia
    videoUrl: ""        // URL do vídeo começa como string vazia
  });
  
  const [message, setMessage] = useState("");

  function onInputChange(evt) {
    // Mudança: O estado do `campaign` é atualizado corretamente com base no id do input.
    setCampaign(prevState => ({ ...prevState, [evt.target.id]: evt.target.value }));
  }

  function btnSaveClick() {
    setMessage("Salvando... Aguarde...");
    addCampaign(campaign)
      .then(tx => getLastCampignId())
      .then(id => setMessage(`Campanha salva com o ID <b>${id}, Avise aos seus amigos e passe a eles este número.</b>`))
      .catch(err => {
        console.error(err);
        setMessage(err.message);
      });
  }

  return (
    <>
      <Head>
        <title>Donate Crypto | Criar nova campanha</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container">
        <h1 className="display-5 fw-bold text-body-enphasis lh-1 mb-3">
          Donate Crypto
        </h1>
        <p>Preencha os campos para incluir sua campanha na plataforma.</p>
        <hr className="mb-4" />
        <div className="col-6">
          <div className="form-floating mb-3">
            <input
              type="text"
              id="title"
              className="form-control"
              // Mudança: O valor inicial é controlado pelo estado `campaign.title`
              value={campaign.title}
              onChange={onInputChange}
            />
            <label htmlFor="title">Título: </label>
          </div>
          <div className="form-floating mb-3">
            <textarea
              id="description"
              className="form-control"
              // Mudança: O valor inicial é controlado pelo estado `campaign.description`
              value={campaign.description}
              onChange={onInputChange}
            ></textarea>
            <label htmlFor="description">Descrição: </label>
          </div>
          <div className="form-floating mb-3">
            <input
              type="text"
              id="imageUrl"
              className="form-control"
              // Mudança: O valor inicial é controlado pelo estado `campaign.imageUrl`
              value={campaign.imageUrl}
              onChange={onInputChange}
            />
            <label htmlFor="imageUrl">URL da imagem: </label>
          </div>
          <div className="form-floating mb-3">
            <input
              type="text"
              id="videoUrl"
              className="form-control"
              // Mudança: O valor inicial é controlado pelo estado `campaign.videoUrl`
              value={campaign.videoUrl}
              onChange={onInputChange}
            />
            <label htmlFor="videoUrl">URL do vídeo: </label>
          </div>
        </div>
        <div className="col-6">
          <input
            type="submit"
            className="btn btn-primary col-12 p-3 mb-2"
            value="Salvar campanha"
            onClick={btnSaveClick}
          />
        </div>
        <div className="col-6">
          <Link href="/" className="btn btn-secondary col-12 p-3">
            Voltar
          </Link>
        </div>
      </div>
      {message ? (
        <div className="alert alert-success p-3 col-6" role="alert">
          {message}
        </div>
      ) : (
        <></>
      )}
      <Footer />
    </>
  );
}
