import Footer from "@/components/Footer";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { getCampaign, donate } from "@/services/web3Service";

export default function Donate() {
  const [campaign, setCampaign] = useState({
    title: "",
    description: "",
    imageUrl: "",
    videoUrl: "",
  });
  const [donation, setDonation] = useState(0);
  const [message, setMessage] = useState("");

  function onChangeId(evt) {
    campaign.id = evt.target.value;
  }

  function onInputChange(evt) {
    setCampaign((prevState) => ({
      ...prevState,
      [evt.target.id]: evt.target.value,
    }));
  }

  function btnSearchClick() {
    setMessage("Buscando... Aguarde...");
    getCampaign(campaign.id)
      .then((result) => {
        setMessage("");
        result.id = campaign.id;
        setCampaign(result);
      })
      .catch((err) => setMessage(err.message));
  }

  function serializeBigInt(obj) {
    return JSON.parse(
      JSON.stringify(obj, (key, value) =>
        typeof value === "bigint" ? value.toString() : value
      )
    );
  }

  function onChangeValue(evt){
    setDonation(evt.target.value)
  }

  function btnDonateClick(){
    setMessage("Doando... Aguarde...")
    donate(campaign.id, donation)
      .then(tx=> setMessage(`Doação realizada, em alguns minutos o saldo será atualizado.`))
      .catch(err=> setMessage(err.message));
  }

  return (
    <>
      <Head>
        <title>Donate Crypto | Fazer Doação</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container">
        {" "}
        {/* Corrigido: Fechamento de <div> */}
        <h1 className="display-5 fw-bold text-body-enphasis lh-1 mb-3">
          Donate Crypto
        </h1>
        {!campaign.id ? (
          <>
            <p className="mb-5">Qual é o ID da campanha que procura?</p>
            <div className="col-3">
              <div className="input-group mb-3">
                {" "}
                {/* Corrigido: input-group */}
                <input
                  type="number"
                  id="campaign"
                  className="form-control"
                  onChange={onChangeId}
                />
                <input
                  type="button"
                  value="Buscar"
                  className="btn btn-primary p-3"
                  onClick={btnSearchClick}
                />
              </div>
            </div>
          </>
        ) : (
          <>
            <p>
              Verifique se esta é a campanha certa, antes de você finalizar esta
              doação.
            </p>
            <hr />
            <div className="row flex-lg-row-reverse align-items-center g-5">
              <div className="col-7">
                {campaign.videoUrl ? (
                  <iframe
                    width="100%"
                    height="480"
                    src={campaign.videoUrl}
                  ></iframe>
                ) : (
                  <img
                    src={campaign.imageUrl}
                    className="d-block mx-lg-auto img-fluid"
                    width="640"
                    height="480"
                  ></img>
                )}
              </div>
              <div
                className="col-5 mb-5"
                style={{ height: 480, scrollbars: true }}
              >
                <h2>{campaign.title}</h2>
                <p>
                  <strong>Autor:</strong> {campaign.author}
                </p>
                <p className="mb-3 ">{campaign.description}</p>
                {campaign.videoUrl && (
                  <p>
                    Assita nosso vídeo ao lado para entender melhor nossa
                    campanha.
                  </p>
                )}
                <p className="mb-3 fst-italic mt-5">
                  E aí, o que você achou do projeto? Já foi arrecadado o total de  
                  { Number(campaign.balance) / 10 ** 18} BNB nesta campanha. O quanto
                  você quer doar (em BNB)?
                </p>
                <div className="mb-3">
                  <div className="input-group">
                    <input
                      type="number"
                      id="campaign"
                      className="form-control"
                      onChange={onChangeValue}
                      value={donation}
                    />
                    <span className="input-group-text">BNB</span>
                    <input
                      type="button"
                      value="Doar"
                      className="btn btn-primary p-3 w-25"
                      onClick={btnDonateClick}
                    />
                  </div>
                </div>
              </div>
            </div>
          </>
        )}
        {message ? (
          <div className="alert alert-success p-3 col-6" role="alert">
            {message}
          </div>
        ) : (
          <></>
        )}
      </div>
      <Footer />
    </>
  );
}
